### ISSUE TITLE
Not being able to run program because of wrong path being defaulted.

### ISSUE THREAD

**Issue by Ineedgeode** [ErdajtSopjani/AC-unlocker#2]
I ran it via administrator cmd because otherwise it would not run. After that i found out it defaults to the wrong path C;/Program files (x86)/steam/steamapps/common/assetocorsa/ in stead of  C;/Program files (x86)/steam/steamapps/common/assetocorsa/content
and i could not change it to  C;/Program files (x86)/steam/steamapps/common/assetocorsa/content because it would end the file at C:/program and i have not been able to solve it on my own

**Comment by ErdajtSopjani** [comment]
Thank you for reporting the issue.

I noticed this after publishing the release and will get on it as soon as I'm free.

**Comment by ErdajtSopjani** [comment]
Fixed issue and released: https://github.com/ErdajtSopjani/AC-unlocker/releases/tag/1.1
(this code was untested but will work)

If you encounter the problem again open another issue.
