### ISSUE TITLE
Not working or not intentended?

### ISSUE THREAD

**Issue by nknm** [ErdajtSopjani/AC-unlocker#4]
Some DLC maps still claim I dont own them. Is this supposed to work for tracks too? The cars work perfectly thank you so much!

PS: Left a star because the cars part works and its very good + you asked nicely :)

**Comment by ErdajtSopjani** [comment]
> Some DLC maps still claim I dont own them. Is this supposed to work for tracks too? The cars work perfectly thank you so much!
> 
> 
> 
> PS: Left a star because the cars part works and its very good + you asked nicely :)

Hello, thanks :)

This unfortunately isn't meant to work for maps, only for cars.

**Comment by ErdajtSopjani** [comment]
I'm going to close this issue now, but if you have any other concerns please open another one.
